### PR TITLE
some changes + fix + refactor code

### PR DESCRIPTION
**Pull request by Mr-Maslo**
[changes]
- new widget parameters: thumbnailWidth, thumbnailHeight - size of thumbnail block
- "width" and "height" widget parameters now process to UploadAction to overwrite action parameters

[fix]
- fix incorrect usage of thumbnail jQuery object during deleting image process
- some changes in structure of widget: reduced requirements to "crop-widget" block elements

[refactor web/js/cropper.js]
- proxy some jQuery objects using in script
- renamed css-classes from under_score case to kebab-case
- restyle code

[refactor views/widget.php]
- move delete button to button block
- remove 'center-block' class from thumbnail block

### CODE REVIEW

**Comment by budyaga** [comment]
Thanks for pull-request, but why do you want to replace short php tags? As far as I know, since PHP 5.4 echo short tags always enabled.

**Comment by Mr-Maslo** [comment]
IMHO, short php tags less readable in html+php code.

**Comment by budyaga** [comment]
Someone can have another opinion, so let don`t change code style. By the way, Yii2 application templates use short tags too.

**Comment by budyaga** [comment]
@Mr-Maslo could you replace short tags?

**Comment by Mr-Maslo** [comment]
@budyaga ok. It's done.

**Comment by budyaga** [comment]
Thanks!

**Pull request merged**
